FROM node:alpine

RUN apk update && apk upgrade
RUN npm install -g npm@9.1.1
RUN npm install -g yarn --force
RUN npm install serve -g

WORKDIR /app

COPY ./frontend .

RUN yarn
RUN yarn build

EXPOSE 3000

CMD ["yarn", "prod"]
